name: cookbook
description: Application for chefs.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  html: ^0.15.0
  http: ^0.13.4
  sembast: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.8.2

flutter:
  uses-material-design: true
