name: cookbook
description: Application for chefs.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  hive: ^2.2.1
  hive_flutter: ^1.1.0
  html: ^0.15.0
  http: ^0.13.4
  rxdart: ^0.27.4

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
